# example netlify.toml
[build]
  command = "yarn workspace t7chicken.com build"
  functions = "functions"
  publish = "site/t7chicken.com/public"

  ## Uncomment to use this redirect for Single Page Applications like create-react-app. 
  ## Not needed for static site generators.
  #[[redirects]]
  #  from = "/*"
  #  to = "/index.html"
  #  status = 200
  
  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/master/docs/netlify-dev.md#project-detection
  [dev] 
   command = "yarn workspace t7chicken.com start" # Command to start your dev server
   port = 8000 # Port that the dev server will be listening on
   targetPort = 8000
   functionsPort = 34567
   publish = "site/t7chicken.com/public" # Folder with the static content for _redirect file
  
  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/ 
